### ISSUE TITLE
Different commands can't touch the same objects?

### ISSUE THREAD

**Issue by jeremysalwen** [jedrzejboczar/easy-repl#5]
I was unable to get a working example where two different commands modify the same object. The example in the repo shows two different commands affecting two *different* objects, but the borrow checker isn't bothered by that.

**Comment by jedrzejboczar** [comment]
The variables are `move`d into the command handlers, so I guess you'll need some kind of interior mutability, probably something like `RefCell`.

**Comment by jedrzejboczar** [comment]
I added an example which should be helpful: https://github.com/jedrzejboczar/easy-repl/blob/master/examples/shared_mut_state.rs. I just uses two references (non-mutable, so you can hold as many as you want), referencing a `RefCell` (which gives interior mutability). If you return the shell from your function (i.e. it outlives the state variable), instead of references you would have to use  `Rc` and `.clone()` it.
